postgres:
  image: postgres:latest
  container_name: postgreSQL
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: telegrambot
    PGDATA: /var/lib/postgresql/data/pgdata
  ports:
    - "5432:5432"
  volumes:
    - postgres-data:/var/lib/postgresql/data/pgdata
  deploy:
    resources:
      limits:
        cpus: '0.50'
        memory: 512M
      reservations:
        cpus: '0.25'
        memory: 256M
  command: >
    postgres -c max_connections=1000
              -c shared_buffers=256MB
              -c effective_cache_size=768MB
              -c maintenance_work_mem=64MB
              -c checkpoint_completion_target=0.7
              -c wal_buffers=16MB
              -c default_statistics_target=100
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U user -d telegrambot" ]
    interval: 30s
    timeout: 10s
    retries: 5
  restart: unless-stopped
  tty: true
  stdin_open: true

postgres-2:
  image: postgres:latest
  container_name: postgreSQL-2
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: postgres
    PGDATA: /var/lib/postgresql/data/pgdata-logs
    PGPORT: 5433
  ports:
    - "5433:5433"
  volumes:
    - postgres-data:/var/lib/postgresql/data/pgdata-logs
  deploy:
    resources:
      limits:
        cpus: '0.50'
        memory: 512M
      reservations:
        cpus: '0.25'
        memory: 256M
  command: >
    postgres -c max_connections=1000
              -c shared_buffers=256MB
              -c effective_cache_size=768MB
              -c maintenance_work_mem=64MB
              -c checkpoint_completion_target=0.7
              -c wal_buffers=16MB
              -c default_statistics_target=100
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U user -d telegrambotlogs" ]
    interval: 30s
    timeout: 10s
    retries: 5
  restart: unless-stopped
  tty: true
  stdin_open: true