spring:
  application:
    name: backendservice
  kafka:
    bootstrap-servers: 9092
  com:
    backendservice:
      backenddb:
        url: jdbc:postgresql///localhost:5432/backenddb
        username: user
        password: password
        class-driver: org.postgresql.Driver
      logdb:
        url: jdbc:postgresql///localhost:5433/logdb
        username: user
        password: password
        class-driver: org.postgresql.Driver

