spring:
  application:
    name: botservice
  kafka:
    bootstrap-servers: localhost:9092
  server:
    port: 8081


bot:
  token: 7940276562:AAEVnwlS_xEhNEnFZHt04c_b2-vkYu8bFig
  name: "TestTestingTastyBot"